/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedContent: typeof import('./src/components/transitions/AnimatedContent.vue')['default']
    AnimatedList: typeof import('./src/components/layout/AnimatedList.vue')['default']
    Aurora: typeof import('./src/components/backgrounds/Aurora.vue')['default']
    BlurText: typeof import('./src/components/text-effects/BlurText.vue')['default']
    BounceCards: typeof import('./src/components/cards/BounceCards.vue')['default']
    ClickSpark: typeof import('./src/components/interactive/ClickSpark.vue')['default']
    Counter: typeof import('./src/components/text-effects/Counter.vue')['default']
    CountUp: typeof import('./src/components/text-effects/CountUp.vue')['default']
    DeckControls: typeof import('./src/layouts/DeckControls.vue')['default']
    Dock: typeof import('./src/components/layout/Dock.vue')['default']
    DotGrid: typeof import('./src/components/backgrounds/DotGrid.vue')['default']
    ElectricBorder: typeof import('./src/components/cards/ElectricBorder.vue')['default']
    FadeContent: typeof import('./src/components/transitions/FadeContent.vue')['default']
    GlitchText: typeof import('./src/components/text-effects/GlitchText.vue')['default']
    GradientText: typeof import('./src/components/text-effects/GradientText.vue')['default']
    Grainient: typeof import('./src/components/backgrounds/Grainient.vue')['default']
    Lightning: typeof import('./src/components/backgrounds/Lightning.vue')['default']
    LiquidChrome: typeof import('./src/components/backgrounds/LiquidChrome.vue')['default']
    Magnet: typeof import('./src/components/interactive/Magnet.vue')['default']
    Particles: typeof import('./src/components/backgrounds/Particles.vue')['default']
    PixelTransition: typeof import('./src/components/transitions/PixelTransition.vue')['default']
    PopupSelect: typeof import('./src/layouts/PopupSelect.vue')['default']
    PresentationDeck: typeof import('./src/layouts/PresentationDeck.vue')['default']
    RotatingText: typeof import('./src/components/text-effects/RotatingText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrambleText: typeof import('./src/components/text-effects/ScrambleText.vue')['default']
    ShinyText: typeof import('./src/components/text-effects/ShinyText.vue')['default']
    Silk: typeof import('./src/components/backgrounds/Silk.vue')['default']
    SlideOverview: typeof import('./src/layouts/SlideOverview.vue')['default']
    SlideRenderer: typeof import('./src/layouts/SlideRenderer.vue')['default']
    SplitText: typeof import('./src/components/text-effects/SplitText.vue')['default']
    SpotlightCard: typeof import('./src/components/cards/SpotlightCard.vue')['default']
    Stack: typeof import('./src/components/layout/Stack.vue')['default']
    StarBorder: typeof import('./src/components/cards/StarBorder.vue')['default']
    TiltedCard: typeof import('./src/components/cards/TiltedCard.vue')['default']
  }
}
