/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeckControls: typeof import('./src/components/DeckControls.vue')['default']
    PresentationDeck: typeof import('./src/components/PresentationDeck.vue')['default']
    SlideCode: typeof import('./src/layouts/SlideCode.vue')['default']
    SlideComparison: typeof import('./src/layouts/SlideComparison.vue')['default']
    SlideContent: typeof import('./src/layouts/SlideContent.vue')['default']
    SlideCover: typeof import('./src/layouts/SlideCover.vue')['default']
    SlideImageGrid: typeof import('./src/layouts/SlideImageGrid.vue')['default']
    SlideList: typeof import('./src/layouts/SlideList.vue')['default']
    SlideMedia: typeof import('./src/layouts/SlideMedia.vue')['default']
    SlideOverview: typeof import('./src/components/SlideOverview.vue')['default']
    SlideQuote: typeof import('./src/layouts/SlideQuote.vue')['default']
    SlideRenderer: typeof import('./src/components/SlideRenderer.vue')['default']
    SlideSection: typeof import('./src/layouts/SlideSection.vue')['default']
    SlideStats: typeof import('./src/layouts/SlideStats.vue')['default']
    SlideTimeline: typeof import('./src/layouts/SlideTimeline.vue')['default']
    SlideTwoColumn: typeof import('./src/layouts/SlideTwoColumn.vue')['default']
  }
}
