/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeckControls: typeof import('./src/components/DeckControls.vue')['default']
    PresentationDeck: typeof import('./src/components/PresentationDeck.vue')['default']
    SlideCode: typeof import('./src/components/SlideCode.vue')['default']
    SlideContent: typeof import('./src/components/SlideContent.vue')['default']
    SlideCover: typeof import('./src/components/SlideCover.vue')['default']
    SlideMedia: typeof import('./src/components/SlideMedia.vue')['default']
    SlideOverview: typeof import('./src/components/SlideOverview.vue')['default']
    SlideQuote: typeof import('./src/components/SlideQuote.vue')['default']
    SlideRenderer: typeof import('./src/components/SlideRenderer.vue')['default']
    SlideSection: typeof import('./src/components/SlideSection.vue')['default']
    SlideStats: typeof import('./src/components/SlideStats.vue')['default']
    SlideTwoColumn: typeof import('./src/components/SlideTwoColumn.vue')['default']
  }
}
